This document serves as a personal collection of

* tools for package development,
* good practices for programming,
* and most frequently used packages.

The material treated here certainly does not cover all of `R`, but rather serves as list of essential things related to programming in `R` that I find useful to know. The document is partly opinionated and subjective, so feel free to open up an <a href="https://github.com/dirmeier/essential-R/issues">issue</a> if you feel some parts should be clarified or reformulated.

For general references on programming the interested reader is referred to:

- Robert Martin: Clean Code,
- Andrew Hunt: The Pragmatic Programmer,
- Gang of Four: Design Patterns,
- Colin Gillespie: Efficient R programming,
- Patrick Burns: The R Inferno,
- Hadley Wickham: R packages,
- Hadley Wickham: Advanced R,
- Dirk Eddelbuettel: Seamless R and C++ Integration with Rcpp,
- Donald Knuth: The Art of Computer Programming,
- a <a href="http://norvig.com/21-days.html">comment</a> by Peter Norvig,
- ...

# R package development

A minimum `R`-package stack at least consists of the following packages of tools:

- `devtools`
- `testthat`
- `roxygen2`
- `covr`
- `lintr`
- `styler`
- `usethis`
- `remotes`
- `pkgdown`
- `rcmdcheck`
- `profvis`
- `bench`
- `microbenchmark`
- `lobstr`

# Programming

- `purrr`
- `magrittr`
- `R6`
- `rcpp`
- `reticulate`
- `cpp11`


## C++

- gdb and lldb for debugging,
- valgrind and gprof to check for memory leaks and for profiling,
- Intel's Parallel Studio XE (<3) which is a toolbox for vectorization, debugging, memory checks, etc. If you can get hold of it, get it. It is magnificent.
- Boost for unit tests, data structures and basically everything you ever need,
- cppcheck for static code analysis,
- doxygen for code documentation.


- Scott Meyers: Effective Modern C++,
- Scott Meyers: Effective C++,
- Ben Klemens: 21. century C,
- Kurt Guntheroth: Optimized C++,
- Nicolai Josuttis: C++17 - the complete guide,
- David Vandevoorde: C++ Templates - the compete guide.

# Working with data

- tidyverse (dplyr, tidyr, dpplyr, rlang)
- data.table
- datastructures
- data bases
- rlang


# Machine learnign and statistics 

- rstan
- rstanarm
- brms
- loo
- projpred
- bayesplot

- sparklyr
- greta
- coda
- MCMCpack
- tensorflow
- keras
- tfprobability
- mgcv
- kernlab


# Optimization

- nloptr
- cvxr

# plotting

- ggplot
- gpubr
- ggthemes
- hrbrthemes
- ggsci
- ggthemr
- patchwork
- colorblindr, colorspace
- viridis
- cowplot
- scales
- swatches
- plotly
- ggvis
- ggraph
- gganimate
- DiagrammeR

- `ggraph`, `ggnet` and `ggnetwork`
- `gganimate`
- `tweenr`
- `animation`
- `lattice`
- `magick`
- `imager`

- add beautified base plots (tufte or so)
- add colorschemes
- magick and imagr
- scico
- tidygraph
- r2d3

#reporting

- rmarkdown
- bookdown
- tufte
- xaringan
- other standard library for presentations?

# other

shiny
igraph
- compiler

# CI

- github workflows
- appveyor
- travis 
- circle
- coverage
- git
- docker
- 


